### ISSUE TITLE
Favicon Missing

### ISSUE THREAD

**Issue by cravend** [hackchicago/hackchicago#3]
The website is missing a favicon. Do we have a small logo we could use?

**Comment by zanedb** [comment]
Lines 9-22 are commented out in [index.html](https://github.com/hackchicago/hackchicago/blob/8a88db412c6cec97c9e1bbd0e37876a3b7e18a20/index.html#L9). They simply link to [this folder](https://github.com/hackchicago/hackchicago/tree/master/img/icon) of images that contain the old Chicago Hacks logo. There is currently no small size of the Hack Chicago logo and therefore no favicon.

**Comment by itsmingjie** [comment]
Fixed with commit ac34d64126f7353fcdc132f0b20f13c58597242e
