### ISSUE TITLE
Flickering image on hover

### ISSUE THREAD

**Issue by itsmingjie** [hackchicago/hackchicago#7]
For some reasons... This is just triggering my poor mind a lot. I'm not able to screenshot it because the flicker happens in between frames of a gif... 

For reference, I'm talking about these images that have hover effects on them. They flicker every time my mouse moves out of them. Again, flicker does not show up on the gif.

![2018-05-03 22 33 38](https://user-images.githubusercontent.com/13333578/39611032-5b24746a-4f22-11e8-86ea-1f13031dbce7.gif)

**Comment by zanedb** [comment]
Unable to replicate in latest Firefox (v60) on Ubuntu. What browser/OS are you running @mj66?

**Comment by itsmingjie** [comment]
This might be ridiculous but... Fixed in Chrome Dev 68.0.3432.3.
